title: Harrington Life
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.2394658
  brandStrength: 0.4881848
  lightness: 0.3012889
  brandColors:
    - '#8CCBF6'
    - '#181F2F'
    - '#41698C'
    - '#BC5C44'
    - '#AA2441'
  rhythmicContrast: 0.4424133
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Harrington Life
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3388829
layout_spectrum: 1
